# Generated by Django 4.2.30 on 2026-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='en_progreso', max_length=20, verbose_name='Estado')),
                ('total_fichadas', models.IntegerField(default=0, verbose_name='Total fichadas')),
            ],
            options={
                'verbose_name': 'Ciclo de lectura',
                'verbose_name_plural': 'Ciclos de lectura',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('ip', models.CharField(max_length=45, verbose_name='Direccion IP')),
                ('puerto', models.IntegerField(default=4370, verbose_name='Puerto')),
                ('password', models.IntegerField(default=0, verbose_name='Password')),
                ('idadm', models.IntegerField(default=0, verbose_name='ID Administracion')),
                ('es_lector', models.BooleanField(default=False, verbose_name='Es solo lector')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_ciclo', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo ciclo')),
                ('ultimo_estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Ultimo estado')),
                ('ultimo_error', models.TextField(blank=True, verbose_name='Ultimo error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reloj',
                'verbose_name_plural': 'Relojes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloj_nombre', models.CharField(max_length=100, verbose_name='Reloj')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/Hora')),
                ('operacion', models.CharField(max_length=100, verbose_name='Operacion')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('advertencia', models.BooleanField(default=False, verbose_name='Advertencia')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='relojes.ciclolectura', verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Entrada de log',
                'verbose_name_plural': 'Entradas de log',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ciclolectura',
            name='relojes',
            field=models.ManyToManyField(blank=True, to='relojes.reloj', verbose_name='Relojes'),
        ),
    ]
