# Generated by Django 4.2.30 on 2026-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relojes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('expresion_cron', models.CharField(max_length=100, verbose_name='Expresión CRON')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('relojes', models.ManyToManyField(blank=True, to='relojes.reloj', verbose_name='Relojes')),
            ],
            options={
                'verbose_name': 'Tarea programada',
                'verbose_name_plural': 'Tareas programadas',
                'ordering': ['nombre'],
            },
        ),
    ]
