# Generated by Django 4.2.30 on 2026-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relojes', '0002_tareaprogramada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='ultimo_ciclo_ok',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo ciclo exitoso'),
        ),
    ]
